spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/omegaDB
    username: admin
    password: admin
  liquibase:
    change-log: classpath:liquibase/master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

logging:
  level:
    com:
      example:
        omega: DEBUG
    org:
      springframework: DEBUG

application:
  name: omega
  version: 1.0.0-SNAPSHOT

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    configUrl: /swagger-ui.html
    path: /swagger-ui.html
  api-docs:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'health',
            'info',
          ]

global:
  exception-handling:
    debug-message: true

omega:
  app:
    jwt-secret: bestSecretKeyEver
    jwt-expiration-ms: 600000
    jwt-refresh-expirations-ms: 60000
