version: '3.8'
services:

  omega-db:
    image: postgres:14.1
    container_name: omega-db
    restart: always
    environment:
      - POSTGRES_DB=omegaDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '6666:5432'
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db-data:
